### ISSUE TITLE
Fix MSVC compilation errors

### ISSUE THREAD

**Issue by Nanodesy** [Nanodesy/Snake#2]
Fix code compilation errors when compiling using the MSVC compiler during CI pipeline builds.

At the moment, the matrix lines for the MSVC compiler are commented out in the .github/workflows/ci.yml file. It is necessary to uncomment them and solve compilation errors.

```
    strategy:
      fail-fast: false
      matrix:
        platform:
        # TODO: Fix MCVS compilation.
        # - { name: Windows VS2019, os: windows-2019  }
        # - { name: Windows VS2022, os: windows-2022  }
        - { name: Linux GCC,      os: ubuntu-latest }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,          os: macos-latest  }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }
```

Unfortunately, at the moment I have no idea why the errors occurred and cannot help with advice. You can try running pipeline jobs and examine the errors.
